[snowflake]
user_name = "guest_ZheWNtmM"
password = "ie6uVad2#"
account = "ui76830.west-europe.azure"
database = "CODE_CHALLENGE_ZHEWNTMM"
schema = "SOURCE"
warehouse = "GUEST_CODE_CHALLENGE_ZHEWNTMM"
role = "GUEST_CODE_CHALLENGE_ZHEWNTMM"
